### ISSUE TITLE
websocket support

### ISSUE THREAD

**Issue by zxr90** [1Forge/golang-forex-quotes#3]
Do you have plans to include websocket support for go?

**Comment by brutus-gr** [comment]
@zxr90 This is something we'd like to eventually add, however, we don't have the bandwidth to do it now.  We welcome any PRs adding this functionality.

**Comment by brutus-gr** [comment]
@zxr90 The library now has WebSocket support.  Thanks for your patience.

**Comment by zxr90** [comment]
thank you for the update!
